namespace: tanzu-system-dashboards
grafana:
  deployment:
    replicas: 1
    containers:
      resources:
    podLabels: {}
    podAnnotations: {}
    k8sSidecar:
      containers:
        resources:
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    labels: {}
    annotations: {}
  config:
    grafana_ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.com
      [log]
      mode = console
      [paths]
      data = /var/lib/grafana/data
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
    datasource_yaml: |-
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: prometheus-server.tanzu-system-monitoring.svc.cluster.local
          access: proxy
          isDefault: true
    dashboardProvider_yaml: |-
      apiVersion: 1
      providers:
        - name: 'sidecarDashboardProvider'
          orgId: 1
          folder: ''
          folderUid: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /tmp/dashboards
            foldersFromFilesStructure: true
  pvc:
    annotations: {}
    storageClassName: iscsi
    accessMode: ReadWriteOnce
    storage: "2Gi"
  secret:
    type: "Opaque"
    admin_user: "YWRtaW4="
    admin_password: "Vm13YXJlMSE="
ingress:
  enabled: true
  virtual_host_fqdn: "grafana.tkg-workload1.vmwire.com"
  prefix: "/"
  servicePort: 80
  tlsCertificate:
    tls.crt: |
      -----BEGIN CERTIFICATE-----
      MIIEcTCCA1mgAwIBAgISA2402M1+I7Mdi20Efe+heB+PMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzAzMjQxMjI0MjJaFw0yMzA2MjIxMjI0MjFaMCUxIzAhBgNVBAMM
      GioudGtnLXdvcmtsb2FkMS52bXdpcmUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0D
      AQcDQgAEfpK61D9lY2AFsvGpfHpFSDaYujQt6M9gmraHk0nrHraMI+HK6Axm1brG
      V0skwlCXKkZSBo4TfaeL1zn257C5BKOCAlcwggJTMA4GA1UdDwEB/wQEAwIHgDAd
      BgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNV
      HQ4EFgQUqV32vU8c9yDTicsUBbB0Q40SldYwHwYDVR0jBBgwFoAUFC6zF7dYVsuu
      UAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8v
      cjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9y
      Zy8wJQYDVR0RBB4wHIIaKi50a2ctd29ya2xvYWQxLnZtd2lyZS5jb20wTAYDVR0g
      BEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0
      cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEGBgorBgEEAdZ5AgQCBIH3BIH0APIA
      dwB6MoxU2LcttiDqOOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAYcTyq52AAAEAwBI
      MEYCIQDzFMJIZOsJ0oFA5vQUf5JYAIZkwA2y14Ov+ycq54d6fgIhALNrcg3Ik6Yl
      Le1mQ8qUfkm5k1E6AH588RaafdfXN52BAHcA6D7Q2j71BjUy51covIlryQPTy9ER
      a+zraeF3fW0GvW4AAAGHE8quVQAABAMASDBGAiEAoVsvqo8ZGj4rk3wXf/LeJCBl
      MBH6PZAoe21UdnJ9i8oCIQDj2KT5yiT8kQv1rzlWQh/xuzVTiPkdvPG/vqwrtIhc
      2DANBgkqhkiG9w0BAQsFAAOCAQEAEs9JI1pgtzObrFgtVzlsQnd/12/Pad9Yr6YS
      TNW3qulIahFxP7UqTHOLUHl4pgiM8qgferhrLvWnMp9IqCrUTISJqQnXyny28p6g
      2scjKlEIkvEDopLhzM2tjBzw8kWTaGXPO23GappGYmx9/LkcdP5RKLJ2iQLBWfXS
      cPFSfek2HG7tL57K4R+xx0x17lgdKxWN/RXCdopqOctrL+O/IpYUVesbW3InJEd9
      v6fKTfTO8+rUVydj5fPgEQbokd6/pCLgHa/5QZP26ug+QkYePBoQdkNJF998kcGY
      Adg4LzIf7XuOR40xyOthr27ZxcQWfxL3c8lbnRRk1vM/zL08Hw==
      -----END CERTIFICATE-----

    tls.key: |
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgWHV39Lytc2T4NzMc
      XeirEmLMicfvd7fnGxp0CJiY+4KhRANCAAR+krrUP2VjYAWy8al8ekVINpi6NC3o
      z2CatoeTSesetowj4croDGbVusZXSyTCUJcqRlIGjhN9p4vXOfbnsLkE
      -----END PRIVATE KEY-----

    ca.crt:
