---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hackazon-deployment
  labels:
    app: hackazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackazon
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
        - name: hackazon
          image: ianwijaya/hackazon
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      imagePullSecrets:
      - name: regcred
---
kind: Service
apiVersion: v1
metadata:
  name: hackazon-service
  labels:
    svc: hackazon
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: hackazon
  type: ClusterIP
