---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackazon-ingress
  annotations:
    ako.vmware.com/enable-tls: "true"
  labels:
    app: hackazon
spec:
  ingressClassName: aviingressclass-tkg-workload-vip
  rules:
    - host: "hackazon.tkg-workload1.vmwire.com"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: hackazon-service
                port:
                  number: 80
