namespace: tanzu-system-dashboards
grafana:
  deployment:
    replicas: 1
    containers:
      resources:
    podLabels: {}
    podAnnotations: {}
    k8sSidecar:
      containers:
        resources:
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    labels: {}
    annotations: {}
  config:
    grafana_ini: |
      [analytics]
      check_for_updates = false
      [grafana_net]
      url = https://grafana.com
      [log]
      mode = console
      [paths]
      data = /var/lib/grafana/data
      logs = /var/log/grafana
      plugins = /var/lib/grafana/plugins
      provisioning = /etc/grafana/provisioning
    datasource_yaml: |-
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: prometheus-server.tanzu-system-monitoring.svc.cluster.local
          access: proxy
          isDefault: true
    dashboardProvider_yaml: |-
      apiVersion: 1
      providers:
        - name: 'sidecarDashboardProvider'
          orgId: 1
          folder: ''
          folderUid: ''
          type: file
          disableDeletion: false
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /tmp/dashboards
            foldersFromFilesStructure: true
  pvc:
    annotations: {}
    storageClassName: null
    accessMode: ReadWriteOnce
    storage: "2Gi"
  secret:
    type: "Opaque"
    admin_user: "YWRtaW4="
    admin_password: "Vm13YXJlMSE="
ingress:
  enabled: true
  virtual_host_fqdn: "grafana.tkg-1.vmwire.com"
  prefix: "/"
  servicePort: 80
  tlsCertificate:
    tls.crt: |
      -----BEGIN CERTIFICATE-----
      MIIFKzCCBBOgAwIBAgISAy5Vu+pPgJhlaB5nHhujxX6OMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMjExMjAwOTIzMDRaFw0yMzAyMTgwOTIzMDNaMB0xGzAZBgNVBAMM
      EioudGtnLTEudm13aXJlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
      ggEBALJiHKrff8J8jOjcWkn5HcQNadwfqHON60sOxd+yLSsZs9jauS3XYB6fhRZT
      p0aTpHwiwrIAnEUi1VD3Zvv7Is2/tXMGH/96vviNAFN1NiWxGTbGg0RfS/DKWkpj
      LDmZAVt/kAYP/M8r4o4Ub2eXHOY9JXTb3AdufMGNRGQR//svuPLl/joxNrw8KTIa
      7osKoQHGpk+N1JdJZNqFGU9bFE+wZi1wOEJ1/9DXH0mORuNoYZfYYKZGNY81Htd2
      sqgx8DTDs/JcdW3zHOWjHWNF5KWroRBi45dVcAgy7t5QYPjRjw3UqDV5IiMv70zI
      XQUhH0fhlJiyIeDsD/uGV7S7zPsCAwEAAaOCAk4wggJKMA4GA1UdDwEB/wQEAwIF
      oDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAd
      BgNVHQ4EFgQUGbtLWMabOuCOnLN8SFqZ2D1pyKIwHwYDVR0jBBgwFoAUFC6zF7dY
      VsuuUAlA5h+vnYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRw
      Oi8vcjMuby5sZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNy
      Lm9yZy8wHQYDVR0RBBYwFIISKi50a2ctMS52bXdpcmUuY29tMEwGA1UdIARFMEMw
      CAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9j
      cHMubGV0c2VuY3J5cHQub3JnMIIBBQYKKwYBBAHWeQIEAgSB9gSB8wDxAHcAb1N2
      rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAGElJAgXwAABAMASDBGAiEA
      skseHWzm6l8V5QFbjDHiHUXJHWjdaTyo4HGkg2KdwRgCIQCTLuIqVyQVv+vFoZaR
      ligYCPNrM2JbAcL/aAPwyeXsMQB2ALc++yTfnE26dfI5xbpY9Gxd/ELPep81xJ4d
      CYEl7bSZAAABhJSQIXwAAAQDAEcwRQIgW2OWQF7cwHyKrocd4tjJDF0EuxlXzkWz
      c2wjxmJoF5oCIQDTglXFySyp309+uEbPK5C2zgPrgFpbl+pCTNCPcbZEqjANBgkq
      hkiG9w0BAQsFAAOCAQEAcTFFCPjHS6wlKdqSTNxLd0KjOkliJafwxTwdFMC+mO5Q
      fjj4wD/I10Z+9z6uVYvhk3SI48LM1H0Z9F9eAj5omJHYGl0eBU6gtJwzujpsbKMB
      iPxtLPQTkRjGqhZIXnDsLD2i0tIjiZEPSkGUr3XN8JCnv7c49ssOMmOXKQqCMPqC
      mIZ23ViNc+i+ohPY7WH3sNJD23TF34tdcqCr1Me1pizVXvQwKNrjhj/YGojKF7Ut
      s5RM6vfzwSWbD2pyIMR0YBui3adQ8XiWJzJzMvY0qtpAIQ6dagTwVzpzn0dWH+Iq
      Ez+KOefdzNrw/fTS/ZVQMQPxrz6NYntS3pOfnUlxMg==
      -----END CERTIFICATE-----

    tls.key: |
      

    ca.crt:
