grafana:
  deployment:
    replicas: 1
    updateStrategy: Recreate
  pvc:
    accessMode: ReadWriteOnce
    storage: 2Gi
  secret:
    admin_password: Vm13YXJlMSE=
    admin_user: "YWRtaW4="
    type: Opaque
  service:
    port: 80
    targetPort: 3000
    type: ClusterIP
ingress:
  annotations:
    service.beta.kubernetes.io/vcloud-avi-ssl-no-termination: "true"
  enabled: true
  prefix: /
  servicePort: 80
  virtual_host_fqdn: grafana.tenant1.vmwire.com
  tlsCertificate:
    tls.crt: |
      -----BEGIN CERTIFICATE-----
      MIIEZDCCA0ygAwIBAgISA1UHbwcEhpImsiCGFwSMTVQsMA0GCSqGSIb3DQEBCwUA
      MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
      EwJSMzAeFw0yMzA2MTAxMTAwNDFaFw0yMzA5MDgxMTAwNDBaMB8xHTAbBgNVBAMM
      FCoudGVuYW50MS52bXdpcmUuY29tMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
      2jw0rUF7t80MQT1PCG+yBPxvyF/I6gL+9sTUaSx0H2XHVDEkj7wFsdijgIZ6U14O
      ZzkWc2jYGD92IcMqo0H3NKOCAlAwggJMMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUE
      FjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU
      cVqEL70SidS/ftYwEjvHAgGfIoowHwYDVR0jBBgwFoAUFC6zF7dYVsuuUAlA5h+v
      nYsUwsYwVQYIKwYBBQUHAQEESTBHMCEGCCsGAQUFBzABhhVodHRwOi8vcjMuby5s
      ZW5jci5vcmcwIgYIKwYBBQUHMAKGFmh0dHA6Ly9yMy5pLmxlbmNyLm9yZy8wHwYD
      VR0RBBgwFoIUKi50ZW5hbnQxLnZtd2lyZS5jb20wTAYDVR0gBEUwQzAIBgZngQwB
      AgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRz
      ZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwB6MoxU2LcttiDq
      OOBSHumEFnAyE4VNO9IrwTpXo1LrUgAAAYilLhfeAAAEAwBIMEYCIQCi8GNByfoH
      cDgZy0C8dKFfm9E8enJGYEO3qCsS3ewBmQIhAJedkDN5NxWbGGzgRiN73pyfli7F
      DRAwaHj342ZUYXCuAHYAtz77JN+cTbp18jnFulj0bF38Qs96nzXEnh0JgSXttJkA
      AAGIpS4X1AAABAMARzBFAiAIUu9LnclgS7ZcZFgy/hWcsyjwFxt2qPb34JnszGIc
      vgIhAIeNDcbHBfeIiSORgojGyP7gQ/QqB3bUQZxgmmW17v63MA0GCSqGSIb3DQEB
      CwUAA4IBAQCY6eYo1bM1wqCEs/efhayRr98MTTpMmdJL8neCJLQ+c9FYNp2ndLNZ
      GE/x0BNctkyt4kU4YyUcfeNVdF3CyxLs4cqPoFKoxgVvrcQlrcffYg9F7RHzSKT4
      OO1YJ0RM85wKWUPauXb9dugSyL7fvPQ8HRRioHwY5+BCZcIFTjl5TIScJvF2we6d
      fKDfQXk/7+x2QPP4ilKXpTdqwdD1DETSLDLURTstsunXR+WhHMqdln70bUALWlg6
      yZuQH+g+PBGNOC1wbG53oWji67doHE/y0Xfh8wn9kd35EBC48oxNKfRVvbzLVcEG
      NG+wGJRTfKke0ojm8t6BpSpVrhSDXYb4
      -----END CERTIFICATE-----
    tls.key: |

    ca.crt:
namespace: tanzu-system-dashboards