apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.vmwire.com
    tls:
      secretName: kubeapps-host-tls
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
        - name: kubeapps-internal-kubeappsapis
          port: 8080
          protocol: h2c
    - services:
      - name: kubeapps
        port: 80
---
apiVersion: v1
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZIRENDQkFTZ0F3SUJBZ0lTQkR4QzZ2alp0
    R3dqWUI1cDBpNmtnQ0NPTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRN
    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlN
    ekEwTVRFd056TTRNamhhRncweU16QTNNVEF3TnpNNE1qZGFNQmN4RlRBVEJnTlZCQU1NCkRDb3Vk
    bTEzYVhKbExtTnZiVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFP
    SFgKMUNmM2E4eVdrUmlXQnNIZVVETGx6Tkl2aCtYdHdEaS9MVmtEdEZPUUt1bFRwSlNnQ2U4RjRC
    Y29CNlpoVjR1cgpHaXhucldGTlFLREhBSktieUxzUC9PQUtsdXNadXRaWk8rd2NRYURSbjlZekNH
    UE8vSkp5WnFWbnd0am93TkFUCmxFUFNBWndBdyszSzFuc3Q5NEJFQU9Pd1hkTE1LdFBsNFlSdllP
    NEJnSkdiQTZ2cWtPcnNLa2JPdTlZeG50ZVUKbjRPcjIyRXBCMEtFdEE2YTFveW03TkZtRDFSdUtw
    eTFvY2lzUkZ0UXJkenMwc1dzaGFHdFEybllQb0MxZ3FoLwo1NjAveFR6dXVTOVpCRnF3VmxVdEZX
    Mk5mUlRNOHhDcWh2eThjaE9pUnRHejdheldUMFpYalFGT0NNVGZYVDJrCkl5ZzZQdFRaTnRvUFUx
    VGdVVWNDQXdFQUFhT0NBa1V3Z2dKQk1BNEdBMVVkRHdFQi93UUVBd0lGb0RBZEJnTlYKSFNVRUZq
    QVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWRCZ05WSFE0
    RQpGZ1FVUUJkM1Z3SUZjNVNKM3U0TVRHRmtKdTNZampRd0h3WURWUjBqQkJnd0ZvQVVGQzZ6Rjdk
    WVZzdXVVQWxBCjVoK3ZuWXNVd3NZd1ZRWUlLd1lCQlFVSEFRRUVTVEJITUNFR0NDc0dBUVVGQnpB
    QmhoVm9kSFJ3T2k4dmNqTXUKYnk1c1pXNWpjaTV2Y21jd0lnWUlLd1lCQlFVSE1BS0dGbWgwZEhB
    Nkx5OXlNeTVwTG14bGJtTnlMbTl5Wnk4dwpGd1lEVlIwUkJCQXdEb0lNS2k1MmJYZHBjbVV1WTI5
    dE1Fd0dBMVVkSUFSRk1FTXdDQVlHWjRFTUFRSUJNRGNHCkN5c0dBUVFCZ3Q4VEFRRUJNQ2d3SmdZ
    SUt3WUJCUVVIQWdFV0dtaDBkSEE2THk5amNITXViR1YwYzJWdVkzSjUKY0hRdWIzSm5NSUlCQWdZ
    S0t3WUJCQUhXZVFJRUFnU0I4d1NCOEFEdUFIVUFlaktNVk5pM0xiWWc2ampnVWg3cApoQlp3TWhP
    RlRUdlNLOEU2VjZOUzYxSUFBQUdIYjNkbjJnQUFCQU1BUmpCRUFpQWpGemxQUVljdDlYNFVJaUlN
    CndERWNEYWVrcnhhcHEvdnNvT3dETlBYMDl3SWdlY1d2Vlp2U085UGF6RE9UVXh5Zk5nVEtKUUJU
    WlVqVWR3ZW4KNHZnUVVSb0FkUUN0OTc3NmZQOFF5SXVkUFp3ZVBoaHF0R2NwWGMreERDVEtoWVkw
    Njl5Q2lnQUFBWWR2ZDJnRApBQUFFQXdCR01FUUNJRG1TY1hyRm5hUW5YbTZKQkg5alNkVS9SWmdC
    RHJXUVBPMDRNMlNHajNoaUFpQUszNWt5Ck8wOUkxWXMxUG5pSGxqM2E2UnltUFVFWHFQemlNMGFY
    N3FHWmNqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEKc1dRNm1CYWRtZWVZVjlrWjNKOFRCRE9n
    M3JEK3lpU2o3TE1jc1dTNFBmQklUWGpiQTlXTHVJaEJjVXB4Wlp6UQpEYnN4ZXBSclNRekFzV09C
    YjNTK1BoQnMrYU1Sc0JCZmxOanBUc09GWFY0dkpXdkVOaTZOb2xXU3dOV2I4TDh1CnRxTi93S3lm
    TVU2Wk5ad05yYjdhSUlSWi9OWUxNQTAxNUxQYkZLb2c4dStkM3NJT0NPUTlIdVltNXFaRGxXWGIK
    Z0gvWkdnTWNxWmpNMFBETE4zQ01zOHZwa2xEWEtNTHJCcUIrVzZJVDFoSzNNVjlrV1pGSU5tcHdO
    NkwzK3pTNQpzUnZPUGNwYW4xSGc5OUFpN0ducUVSR0xONFFDSnA5YTkxdXVRRFVkbGVkVVdtNzNx
    ekdSZWJMUVVNa1diQUlDCjhGRnc0MDVxc2lDT1VqY2VSNFdGZkE9PQotLS0tLUVORCBDRVJUSUZJ
    Q0FURS0tLS0tCg==
  tls.key: |

kind: Secret
metadata:
  name: kubeapps-host-tls
  namespace: kubeapps
type: kubernetes.io/tls