apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.vmwire.com
    tls:
      secretName: kubeapps-host-tls
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
        - name: kubeapps-internal-kubeappsapis
          port: 8080
          protocol: h2c
    - services:
      - name: kubeapps
        port: 80
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURlVENDQXY2Z0F3SUJBZ0lTQTBtcndyK0NsWlZvN2ZMLzgwT1FuckN1TUFvR0NDcUdTTTQ5QkFNRE1ESXgKQ3pBSkJnTlZCQVlUQWxWVE1SWXdGQVlEVlFRS0V3MU1aWFFuY3lCRmJtTnllWEIwTVFzd0NRWURWUVFERXdKRgpOakFlRncweU5EQTVNREl4TURRMk1EbGFGdzB5TkRFeU1ERXhNRFEyTURoYU1CY3hGVEFUQmdOVkJBTU1EQ291CmRtMTNhWEpsTG1OdmJUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJCRCtJaGpEaFNocndjWTEKYTdZdm01UGtjeldDQXg5MjJ1UmlmUHNHUmc5RktzTWVlNnNGTVpxZExpWHBhY0s4N3JWcjBtcVE5elhabXp2MwprM2xBc0l5amdnSU5NSUlDQ1RBT0JnTlZIUThCQWY4RUJBTUNCNEF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVICkF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZLYUlOSnkycXhaV1JGdncKelEwb0RmQ0hoYWFwTUI4R0ExVWRJd1FZTUJhQUZKTW5ScGdEcVZGb2pwald4RUpJMnlPL1dKVFNNRlVHQ0NzRwpBUVVGQndFQkJFa3dSekFoQmdnckJnRUZCUWN3QVlZVmFIUjBjRG92TDJVMkxtOHViR1Z1WTNJdWIzSm5NQ0lHCkNDc0dBUVVGQnpBQ2hoWm9kSFJ3T2k4dlpUWXVhUzVzWlc1amNpNXZjbWN2TUJjR0ExVWRFUVFRTUE2Q0RDb3UKZG0xM2FYSmxMbU52YlRBVEJnTlZIU0FFRERBS01BZ0dCbWVCREFFQ0FUQ0NBUU1HQ2lzR0FRUUIxbmtDQkFJRQpnZlFFZ2ZFQTd3QjFBRWl3NDJ2YXBrYzBEK1ZxQXZxZE1Pc2NVZ0hMVnQwc2dkbTd2NnM1MklSekFBQUJrYktOCklvWUFBQVFEQUVZd1JBSWdhR0tWMlg2bGQyKzJMS1FWMzZXS2ZjTkVvN3cwWlQ2VGpOaFFjd3dNY1QwQ0lCNWMKMGUvWmhmQzhPUi81OW5wMjJPWmVycHF1a0d1d0R1c0ZuT0w3aFViMkFIWUFHWmdRY1FudzFsSXVNSURTbmo5awp1NE51S016NUQxS083dC9PU2o4V3RNb0FBQUdSc28waS9nQUFCQU1BUnpCRkFpRUE5ZGJxMDRKdlNxWUluM0VMCjc1U1h1TFlQQ3NDd2RPNmVxUXBhenVTam54QUNJR2ZUM3JCYnY4MUo3ZWVwY1Q2ZUI3ZDZoVHRmWHY3R2NKVEIKOVdCZVZtc3BNQW9HQ0NxR1NNNDlCQU1EQTJrQU1HWUNNUURoYTBkSmlRL2I4a3E0YTgyeWx2UElwOURubHROVwpvNU5USi9jUW5JeGo3Qm53SzJEWXlqN0UwaE1aWHhMZmdESUNNUUNRbGxJVDlPeTk0am1nbGRxZmhkbDcvS2s4CjFNbW1QYlgyRXJ5Y2dQbGxjOUc1SlJyR3FySUZqZm9aNjRkSkNJRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ214QldoVTlZUXNMQlJWaWUKZmhvRmdZRGtRaU1Oc1JrVmpjenJpdW5aU0N1aFJBTkNBQVFRL2lJWXc0VW9hOEhHTld1Mkw1dVQ1SE0xZ2dNZgpkdHJrWW56N0JrWVBSU3JESG51ckJUR2FuUzRsNlduQ3ZPNjFhOUpxa1BjMTJaczc5NU41UUxDTQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
kind: Secret
metadata:
  name: kubeapps-host-tls
  namespace: kubeapps
type: kubernetes.io/tls