apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kubeapps-grpc
  namespace: kubeapps
spec:
  virtualhost:
    fqdn: kubeapps.tenant1.vmwire.com
    tls:
      secretName: kubeapps-host-tls
  routes:
    - conditions:
      - prefix: /apis/
      pathRewritePolicy:
        replacePrefix:
        - replacement: /
      services:
        - name: kubeapps-internal-kubeappsapis
          port: 8080
          protocol: h2c
    - services:
      - name: kubeapps
        port: 80
---
apiVersion: v1
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVaRENDQTB5Z0F3SUJBZ0lTQTFVSGJ3Y0Vo
    cEltc2lDR0Z3U01UVlFzTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRN
    Ull3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlN
    ekEyTVRBeE1UQXdOREZhRncweU16QTVNRGd4TVRBd05EQmFNQjh4SFRBYkJnTlZCQU1NCkZDb3Vk
    R1Z1WVc1ME1TNTJiWGRwY21VdVkyOXRNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFn
    QUUKMmp3MHJVRjd0ODBNUVQxUENHK3lCUHh2eUYvSTZnTCs5c1RVYVN4MEgyWEhWREVrajd3RnNk
    aWpnSVo2VTE0TwpaemtXYzJqWUdEOTJJY01xbzBIM05LT0NBbEF3Z2dKTU1BNEdBMVVkRHdFQi93
    UUVBd0lIZ0RBZEJnTlZIU1VFCkZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3REFZRFZS
    MFRBUUgvQkFJd0FEQWRCZ05WSFE0RUZnUVUKY1ZxRUw3MFNpZFMvZnRZd0VqdkhBZ0dmSW9vd0h3
    WURWUjBqQkJnd0ZvQVVGQzZ6RjdkWVZzdXVVQWxBNWgrdgpuWXNVd3NZd1ZRWUlLd1lCQlFVSEFR
    RUVTVEJITUNFR0NDc0dBUVVGQnpBQmhoVm9kSFJ3T2k4dmNqTXVieTVzClpXNWpjaTV2Y21jd0ln
    WUlLd1lCQlFVSE1BS0dGbWgwZEhBNkx5OXlNeTVwTG14bGJtTnlMbTl5Wnk4d0h3WUQKVlIwUkJC
    Z3dGb0lVS2k1MFpXNWhiblF4TG5adGQybHlaUzVqYjIwd1RBWURWUjBnQkVVd1F6QUlCZ1puZ1F3
    QgpBZ0V3TndZTEt3WUJCQUdDM3hNQkFRRXdLREFtQmdnckJnRUZCUWNDQVJZYWFIUjBjRG92TDJO
    d2N5NXNaWFJ6ClpXNWpjbmx3ZEM1dmNtY3dnZ0VGQmdvckJnRUVBZFo1QWdRQ0JJSDJCSUh6QVBF
    QWR3QjZNb3hVMkxjdHRpRHEKT09CU0h1bUVGbkF5RTRWTk85SXJ3VHBYbzFMclVnQUFBWWlsTGhm
    ZUFBQUVBd0JJTUVZQ0lRQ2k4R05CeWZvSApjRGdaeTBDOGRLRmZtOUU4ZW5KR1lFTzNxQ3NTM2V3
    Qm1RSWhBSmVka0RONU54V2JHR3pnUmlONzNweWZsaTdGCkRSQXdhSGozNDJaVVlYQ3VBSFlBdHo3
    N0pOK2NUYnAxOGpuRnVsajBiRjM4UXM5Nm56WEVuaDBKZ1NYdHRKa0EKQUFHSXBTNFgxQUFBQkFN
    QVJ6QkZBaUFJVXU5TG5jbGdTN1pjWkZneS9oV2NzeWp3Rnh0MnFQYjM0Sm5zekdJYwp2Z0loQUll
    TkRjYkhCZmVJaVNPUmdvakd5UDdnUS9RcUIzYlVRWnhnbW1XMTd2NjNNQTBHQ1NxR1NJYjNEUUVC
    CkN3VUFBNElCQVFDWTZlWW8xYk0xd3FDRXMvZWZoYXlScjk4TVRUcE1tZEpMOG5lQ0pMUStjOUZZ
    TnAybmRMTloKR0UveDBCTmN0a3l0NGtVNFl5VWNmZU5WZEYzQ3l4THM0Y3FQb0ZLb3hnVnZyY1Fs
    cmNmZllnOUY3Ukh6U0tUNApPTzFZSjBSTTg1d0tXVVBhdVhiOWR1Z1N5TDdmdlBROEhSUmlvSHdZ
    NStCQ1pjSUZUamw1VElTY0p2RjJ3ZTZkCmZLRGZRWGsvNyt4MlFQUDRpbEtYcFRkcXdkRDFERVRT
    TERMVVJUc3RzdW5YUitXaEhNcWRsbjcwYlVBTFdsZzYKeVp1UUgrZytQQkdOT0Mxd2JHNTNvV2pp
    Njdkb0hFL3kwWGZoOHduOWtkMzVFQkM0OG94TktmUlZ2YnpMVmNFRwpORyt3R0pSVGZLa2Uwb2pt
    OHQ2QnBTcFZyaFNEWFliNAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdT
    TTQ5QXdFSEJHMHdhd0lCQVFRZ2J2RmZzQ0ZoNU1OaklmVVgKZmFnMVJ4Njc3OWs2L3Z2eUlmY0pi
    Q0dFcWFLaFJBTkNBQVRhUERTdFFYdTN6UXhCUFU4SWI3SUUvRy9JWDhqcQpBdjcyeE5ScExIUWZa
    Y2RVTVNTUHZBV3gyS09BaG5wVFhnNW5PUlp6YU5nWVAzWWh3eXFqUWZjMAotLS0tLUVORCBQUklW
    QVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: kubeapps-host-tls
  namespace: kubeapps
type: kubernetes.io/tls