kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  storagePolicyName: iscsi